language: python
python:
    - '3.6'
install:
    - pip install --upgrade pip setuptools wheel
    - pip install pipenv
    - pipenv install -d
script:
    - pipenv run test
after_success:
    - codecov
notifications:
    email: false
